apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-app
data:
  REDIS_HOST: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - name: vote-app
          image: romarcablao/app-vote:1.0
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: vote-app
                  key: REDIS_HOST
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  type: NodePort
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
