configuration:
  backupStorageLocation:
    - bucket: velero-s3-bucket
      provider: aws
  volumeSnapshotLocation:
    - config:
        region: us-west-2
      provider: aws
  initContainers:
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.5.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.7.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  credentials:
    useSecret: false
  serviceAccount:
    server:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::111111111111:role/eks-velero-backup"
